import type { QrDesignPreset } from './types'

export const QR_PRESETS: QrDesignPreset[] = [
  {
    id: 'classic',
    name: 'Classic',
    description: 'Square dots',
    options: {
      foreground: '#000000',
      background: '#ffffff',
      transparentBackground: true,
      dotsStyle: 'square',
      cornersSquareStyle: 'square',
      cornersDotStyle: 'square',
      margin: 12,
      logoScale: 0.18,
    },
  },
  {
    id: 'rounded',
    name: 'Rounded',
    description: 'Soft corners',
    options: {
      foreground: '#000000',
      background: '#ffffff',
      transparentBackground: true,
      dotsStyle: 'rounded',
      cornersSquareStyle: 'extra-rounded',
      cornersDotStyle: 'dot',
      margin: 14,
      logoScale: 0.2,
    },
  },
  {
    id: 'dots',
    name: 'Dots',
    description: 'Circle dots',
    options: {
      foreground: '#000000',
      background: '#ffffff',
      transparentBackground: true,
      dotsStyle: 'dots',
      cornersSquareStyle: 'dot',
      cornersDotStyle: 'dot',
      margin: 14,
      logoScale: 0.2,
    },
  },
  {
    id: 'classy',
    name: 'Classy',
    description: 'Sharp & elegant',
    options: {
      foreground: '#000000',
      background: '#ffffff',
      transparentBackground: true,
      dotsStyle: 'classy',
      cornersSquareStyle: 'square',
      cornersDotStyle: 'square',
      margin: 12,
      logoScale: 0.18,
    },
  },
  {
    id: 'classy_rounded',
    name: 'Classy+',
    description: 'Elegant & soft',
    options: {
      foreground: '#000000',
      background: '#ffffff',
      transparentBackground: true,
      dotsStyle: 'classy-rounded',
      cornersSquareStyle: 'extra-rounded',
      cornersDotStyle: 'dot',
      margin: 14,
      logoScale: 0.2,
    },
  },
  {
    id: 'extra_rounded',
    name: 'Bubble',
    description: 'Max rounded',
    options: {
      foreground: '#000000',
      background: '#ffffff',
      transparentBackground: true,
      dotsStyle: 'extra-rounded',
      cornersSquareStyle: 'extra-rounded',
      cornersDotStyle: 'dot',
      margin: 14,
      logoScale: 0.2,
    },
  },
]
